### ISSUE TITLE
Automatic chart detection

### ISSUE THREAD

**Issue by lucapette** [lucapette/deloominator#17]
# Context

This is the core feature of deloominator and its basic functionalities are described [here](https://github.com/lucapette/deloominator/blob/55d17f9a72ff485c05fe8a6824621b968c18a0e9/docs/charts.md).

The goal of this feature is detecting at least one graph and display it in the playground section.

# Tasks

- [x] Define types and return them for each column (done in #20)
- [x] Introduce the graphql query for charts (done in #21)
- [x] Display a pie chart with two columns (done in #21)
