### ISSUE TITLE
Q&A section

### ISSUE THREAD

**Issue by lucapette** [lucapette/deloominator#32]
# Context

# Tasks

- [x] introduce deluminator database
- [x] introduce auto migrations
- [x] graphql mutations for saving/editing/deleting q&a
- [x] Introduce save feature in the playground
- [x] Basic list of question

**Comment by lucapette** [comment]
Being done in #33
