### ISSUE TITLE
Playground section

### ISSUE THREAD

**Issue by lucapette** [lucapette/deloominator#4]
## Context

The playground is the place where users explore their datasets. The interface
presents a SQL editor, a data source selector and  call to action that runs
queries. It looks like this:

![playground](https://cloud.githubusercontent.com/assets/124274/24627466/4627db00-18b5-11e7-98cd-a2b53024b472.png)

Running a query in the playground has four possible outcomes:

- Error
  There is a problem with the query.
- No data display
  The query is fine but there are no data to return.
- Chart display
  `deloominator` chose to display the data as a chart. Please refer to [this  document](https://github.com/lucapette/deloominator/blob/55d17f9a72ff485c05fe8a6824621b968c18a0e9/docs/charts.md) for further information.
- Raw data display
  `deloominator` will use this option only if there is no way to display the data as a chart.

## Tasks

- [x] [GraphQL endpoint](https://github.com/lucapette/deloominator/issues/6)
- [x] [Introduce react  toolchain](https://github.com/lucapette/deloominator/issues/5)  
- [x] [Simple UI for the playground](https://github.com/lucapette/deloominator/issues/7)
